name: experimental
description: This is my personal OS image.

base-image: ghcr.io/secureblue/securecore-main-hardened
image-version: latest

modules:
  - type: script
    source: ghcr.io/blue-build/modules@sha256:3c04c323f281bdb1ab88148a2335608344bcc07c6c4d2f5f777063a16554256d
    scripts:
      - installselinuxpolicies.sh
  - type: dnf
    source: ghcr.io/blue-build/modules@sha256:3c04c323f281bdb1ab88148a2335608344bcc07c6c4d2f5f777063a16554256d
    install:
      install-weak-deps: false
      packages:
        - qbittorrent-nox
        - libnatpmp
  - type: signing
    source: ghcr.io/blue-build/modules@sha256:3c04c323f281bdb1ab88148a2335608344bcc07c6c4d2f5f777063a16554256d
