name: experimental
description: This is my personal OS image.

base-image: ghcr.io/secureblue/securecore-main-hardened
image-version: latest

modules:
  - type: script
    scripts:
      - installselinuxpolicies.sh
  - type: dnf
    packages:
      install:
        - qbittorrent-nox
        - libnatpmp
  - type: signing
