name: bluebuild
on:
  schedule:
    - cron:
        "00 09 * * *"
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - "**.md"

  workflow_dispatch: 
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:

      - name: Optimize build times
        shell: bash
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update
          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf

      - name: Free disk space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo docker image prune --all --force || true
          sudo swapoff -a || true
          sudo rm -f /mnt/swapfile || true

      - name: Checkout repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Build Custom Image
        uses: blue-build/github-action@785ecb253aee6ead01454ed5bd070c2921010602 # v1.9.1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          cli_version: v0.9.24
          maximize_build_space: false
          squash: true
          skip_checkout: true
          use_cache: false
          retry_push_count: 3
